### ISSUE TITLE
Add tests covering the content of GeoJSON properties

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-quality-analyst#131]
Since #100, the result (GeoJSON properties) were lacking the report metadata and results. This was fixed in #130. To prevent an issue like that in the future tests should be added to check if all necessary (or at least the ones read by the website) properties are set.

Probably using `get_report_properties_template()` would solve a lot of the problems.

**Comment by matthiasschaub** [comment]
`tests/integrationtests/api_response_schema.py` has already a response template for report properties definied. 

The logic in `tests/integrationtests/api_response_schema.py` should be reduced to a minimum. This would mean that there will be a `get_indicator_schema` and `get_report_schema` function instead of a single `get_feature_schema` function.
