### ISSUE TITLE
switch to a parameter-set without camelCase written variables and parameters

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-quality-analyst#162]
Why don't we switch to a parameter-set without camelCase written variables and parameters?

_Originally posted by @joker234 in https://github.com/GIScience/ohsome-quality-analyst/pull/102#r695117960_

-------

I would like to switch to parameter names in the style of `parameter-name` for the API parameters. But I guess this would be a task for another PR.

_Originally posted by @matthiasschaub in https://github.com/GIScience/ohsome-quality-analyst/pull/102#r696488130_

**Comment by matthiasschaub** [comment]
Also we should use "nouns instead of verbs in endpoint paths" as this is considered best practice (see links below). The OQT API already uses nouns and no verbs.

`/indicatorNames` would be translated into `indicator-names` or `indicator/names` or `indicator/list`

REST API Best Practices References:
- https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/#h-use-nouns-instead-of-verbs-in-endpoint-paths
- https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9
