### ISSUE TITLE
Some markers on the map of the website are displaced

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#31]
E.g. https://oqt.ohsome.org/?countryID=43&topic=MapActionPoc

I guess this is due to the geometry not being a bbox anymore but a proper multipolygon (At least in the case of Haiti).

**Comment by Hagellach37** [comment]
Hey @matthiasschaub ,
it is not really displaced, but represents the centroid of the polygon geometry. In the case of Haiti this is in the middle of the ocean. I think that in the case of Haiti it might be more important to adjust to the right zoom level so that the entire polygon is displayed in the map.

About the "displaced" marker we can't do much. I think we would not want to place these markers manually, so from my side it would be okay if it is still in the ocean.
